[phases.setup]
nixPkgs = ['php84', 'nodejs', 'npm', 'composer']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev --no-interaction --ignore-platform-reqs',
    'npm ci --production',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan optimize',
    'php artisan config:cache',
    'php artisan route:cache', 
    'php artisan view:cache',
    'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'