[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 600
startCommand = "frankenphp run --config /etc/caddy/Caddyfile"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3